@startuml RequestRetransmit

    Title Request Retransmit

    Entity PC   as PC
    Entity ESP32 as ESP32

    ESP32 -> PC : (n) RecordRSSI
    ESP32 -> PC : (n+1) RecordRSSI
    ESP32 -> PC : (n+2) RecordRSSI
    ESP32 -> PC : (n+3) RecordRSSI
    ESP32 -> PC : (n+4) RecordRSSI
    
    ... 

    ESP32 -> PC : (n+5) RequestAck
    hnote over ESP32: IDLE
    ...

    PC -> ESP32: (m) Ack (n+5)

    ESP32 -> PC: (n+6) EndOfTransmission
    PC -> ESP32: (m+1) Ack (n+6)


@enduml