@startuml

!theme mars


'left to right direction
'top to bottom direction
'skinparam nodesep 10
'skinparam ranksep 150
'skinparam linetype polyline

Title Database

map AuthProvider {
    provider_id => <&key> PK, Int,
    provider_name => String
}

together {

    map Image {
        image_id => <&key> PK, int
        data => bytes
    }
    
    map Users {
        user_id      => <&key> PK, Int
        OAuth_provider_id => FK, String
        OAuth_user_Id => Int
    }

}

Users -[hidden]d-> Image




map Project {
    project_id => <&key> PK, Int
    creator_user_id => FK, Int
    image_id  => FK, Int
    coordinates => (Float, Float)
    data => JSON
}
Project::creator_user_id -> Users::user_id
Project::image_id -> Image::image_id

Users ---[hidden]-> Project


Users::OAuth_provider_id -> AuthProvider::provider_id
@enduml
